extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern const GeoLayout wf_area_4_geo[];
extern const GeoLayout wf_area_4[];
extern const Collision wf_area_4_collision[];
extern const MacroObject wf_area_4_macro_objs[];
extern const GeoLayout wf_area_5_geo[];
extern const GeoLayout wf_area_5[];
extern const Collision wf_area_5_collision[];
extern const MacroObject wf_area_5_macro_objs[];
extern const GeoLayout wf_area_6_geo[];
extern const GeoLayout wf_area_6[];
extern const Collision wf_area_6_collision[];
extern const MacroObject wf_area_6_macro_objs[];
extern const GeoLayout wf_area_7_geo[];
extern const GeoLayout wf_area_7[];
extern const Collision wf_area_7_collision[];
extern const MacroObject wf_area_7_macro_objs[];
extern const GeoLayout wf_area_8_geo[];
extern const GeoLayout wf_area_8[];
extern const Collision wf_area_8_collision[];
extern const MacroObject wf_area_8_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_003_lights;
extern Lights1 wf_dl_green_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_f3dlite_material_005_lights;
extern Lights1 wf_dl_green_instantwarp_lights;
extern Lights1 wf_dl_f3dlite_material_006_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern Lights1 wf_dl_f3dlite_material_008_lights;
extern Lights1 wf_dl_green_fake_lights;
extern Lights1 wf_dl_death_floor_lights;
extern Lights1 wf_dl_f3dlite_material_002_lights;
extern Lights1 wf_dl_f3dlite_material_011_lights;
extern Lights1 wf_dl_f3dlite_material_012_lights;
extern Lights1 wf_dl_f3dlite_material_007_lights;
extern Lights1 wf_dl_f3dlite_material_009_lights;
extern Lights1 wf_dl_f3dlite_material_010_lights;
extern Lights1 wf_dl_f3dlite_material_013_lights;
extern Lights1 wf_dl_f3dlite_material_014_lights;
extern Lights1 wf_dl_f3dlite_material_015_lights;
extern Lights1 wf_dl_f3dlite_material_016_lights;
extern u8 wf_dl__2_ci8[];
extern u8 wf_dl__2_pal_rgba16[];
extern u8 wf_dl__7_ci8[];
extern u8 wf_dl__7_pal_rgba16[];
extern u8 wf_dl__11_ci8[];
extern u8 wf_dl__11_pal_rgba16[];
extern u8 wf_dl_trol_ci8[];
extern u8 wf_dl_trol_pal_rgba16[];
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_0[16];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_1[20];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_2[4];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Cube_002_mesh_layer_1_vtx_0[14];
extern Gfx wf_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_002_mesh_layer_1_vtx_1[97];
extern Gfx wf_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cube_002_mesh_layer_1_vtx_2[178];
extern Gfx wf_dl_Cube_002_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Cube_003_mesh_layer_1_vtx_0[166];
extern Gfx wf_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_0[127];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_1[75];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Cylinder_001_mesh_layer_1_vtx_0[206];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_002_mesh_layer_1_vtx_0[206];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Cylinder_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_0[6];
extern Gfx wf_dl_Plane_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_005_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_006_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_006_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_007_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_007_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_008_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_008_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_009_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_009_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_010_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_010_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_011_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_011_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_012_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_012_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_013_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_013_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_014_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_014_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_004_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_004_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_002_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_002_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_005_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_005_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_004_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_004_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Cylinder_006_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_006_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_005_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_005_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Cylinder_007_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_007_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_006_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_006_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Cylinder_008_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_008_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_007_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_007_mesh_layer_5_tri_0[];
extern Vtx wf_dl_Cylinder_009_mesh_layer_1_vtx_0[172];
extern Gfx wf_dl_Cylinder_009_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material_003[];
extern Gfx mat_revert_wf_dl_f3dlite_material_003[];
extern Gfx mat_wf_dl_green[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_005[];
extern Gfx mat_wf_dl_green_instantwarp[];
extern Gfx mat_wf_dl_f3dlite_material_006[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_revert_wf_dl_f3dlite_material_004[];
extern Gfx mat_wf_dl_f3dlite_material_008[];
extern Gfx mat_revert_wf_dl_f3dlite_material_008[];
extern Gfx mat_wf_dl_green_fake[];
extern Gfx mat_wf_dl_death_floor[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_revert_wf_dl_f3dlite_material_002[];
extern Gfx mat_wf_dl_f3dlite_material_011[];
extern Gfx mat_wf_dl_f3dlite_material_012[];
extern Gfx mat_wf_dl_f3dlite_material_007[];
extern Gfx mat_wf_dl_f3dlite_material_009[];
extern Gfx mat_revert_wf_dl_f3dlite_material_009[];
extern Gfx mat_wf_dl_f3dlite_material_010[];
extern Gfx mat_wf_dl_f3dlite_material_013[];
extern Gfx mat_wf_dl_f3dlite_material_014[];
extern Gfx mat_wf_dl_f3dlite_material_015[];
extern Gfx mat_wf_dl_f3dlite_material_016[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_002_mesh_layer_1[];
extern Gfx wf_dl_Cube_003_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_001_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_002_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_003_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_5[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_005_mesh_layer_1[];
extern Gfx wf_dl_Cube_006_mesh_layer_1[];
extern Gfx wf_dl_Cube_007_mesh_layer_1[];
extern Gfx wf_dl_Cube_008_mesh_layer_1[];
extern Gfx wf_dl_Cube_009_mesh_layer_1[];
extern Gfx wf_dl_Cube_010_mesh_layer_1[];
extern Gfx wf_dl_Cube_011_mesh_layer_1[];
extern Gfx wf_dl_Cube_012_mesh_layer_1[];
extern Gfx wf_dl_Cube_013_mesh_layer_1[];
extern Gfx wf_dl_Cube_014_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_004_mesh_layer_1[];
extern Gfx wf_dl_Plane_002_mesh_layer_5[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
extern Gfx wf_dl_Cylinder_005_mesh_layer_1[];
extern Gfx wf_dl_Plane_004_mesh_layer_5[];
extern Gfx wf_dl_Cylinder_006_mesh_layer_1[];
extern Gfx wf_dl_Plane_005_mesh_layer_5[];
extern Gfx wf_dl_Cylinder_007_mesh_layer_1[];
extern Gfx wf_dl_Plane_006_mesh_layer_5[];
extern Gfx wf_dl_Cylinder_008_mesh_layer_1[];
extern Gfx wf_dl_Plane_007_mesh_layer_5[];
extern Gfx wf_dl_Cylinder_009_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
