extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_grass_lights;
extern Lights1 wf_dl_dirt_lights;
extern Lights1 wf_dl_death_floor_lights;
extern u8 wf_dl__0_ci8[];
extern u8 wf_dl__0_pal_rgba16[];
extern u8 wf_dl__15_ci8[];
extern u8 wf_dl__15_pal_rgba16[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_0[83];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cylinder_mesh_layer_1_vtx_1[47];
extern Gfx wf_dl_Cylinder_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_grass[];
extern Gfx mat_revert_wf_dl_grass[];
extern Gfx mat_wf_dl_dirt[];
extern Gfx mat_revert_wf_dl_dirt[];
extern Gfx mat_wf_dl_death_floor[];
extern Gfx wf_dl_Cylinder_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_5[];
extern Gfx wf_dl_material_revert_render_settings[];
