extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_f3dlite_material_002_lights;
extern Lights1 wf_dl_death_floor_lights;
extern Vtx wf_dl_Cube_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_001_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx wf_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_mesh_layer_5_vtx_0[4];
extern Gfx wf_dl_Plane_mesh_layer_5_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx mat_wf_dl_death_floor[];
extern Gfx wf_dl_Cube_mesh_layer_1[];
extern Gfx wf_dl_Cube_001_mesh_layer_1[];
extern Gfx wf_dl_Cube_002_mesh_layer_1[];
extern Gfx wf_dl_Plane_mesh_layer_5[];
extern Gfx wf_dl_material_revert_render_settings[];
