extern const GeoLayout castle_inside_area_1_geo[];
extern const GeoLayout castle_inside_area_1[];
extern const Collision castle_inside_area_1_collision[];
extern const MacroObject castle_inside_area_1_macro_objs[];
extern Lights1 castle_inside_dl_wood_lights;
extern Lights1 castle_inside_dl_f3dlite_material_002_lights;
extern Lights1 castle_inside_dl_f3dlite_material_lights;
extern Lights1 castle_inside_dl_f3dlite_material_001_lights;
extern u8 castle_inside_dl__6_ci8[];
extern u8 castle_inside_dl__6_pal_rgba16[];
extern u8 castle_inside_dl__8_ci8[];
extern u8 castle_inside_dl__8_pal_rgba16[];
extern u8 castle_inside_dl__0_ci8[];
extern u8 castle_inside_dl__0_pal_rgba16[];
extern u8 castle_inside_dl__2_ci8[];
extern u8 castle_inside_dl__2_pal_rgba16[];
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_0[175];
extern Gfx castle_inside_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Cube_mesh_layer_1_vtx_1[4];
extern Gfx castle_inside_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx castle_inside_dl_Plane_002_mesh_layer_1_vtx_0[358];
extern Gfx castle_inside_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx castle_inside_dl_Plane_002_mesh_layer_1_vtx_1[59];
extern Gfx castle_inside_dl_Plane_002_mesh_layer_1_tri_1[];
extern Gfx mat_castle_inside_dl_wood[];
extern Gfx mat_revert_castle_inside_dl_wood[];
extern Gfx mat_castle_inside_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material_002[];
extern Gfx mat_castle_inside_dl_f3dlite_material[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material[];
extern Gfx mat_castle_inside_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_inside_dl_f3dlite_material_001[];
extern Gfx castle_inside_dl_Cube_mesh_layer_1[];
extern Gfx castle_inside_dl_Plane_002_mesh_layer_1[];
extern Gfx castle_inside_dl_material_revert_render_settings[];
